### ISSUE TITLE
'$' Is not defined.

### ISSUE THREAD

**Issue by AJPearson** [HEScriptsPack/BetterHex#5]
Hi there,

Running BetterHex.user.js within tamper monkey I cannot seem to find where '$' is defined. This seems to be throwing up a lot of errors for me?
Am I being silly and missing something?

**Comment by Logfro** [comment]
The "$" is actually jQuery and as it is on every HE page included there is no need to define it urself. But what errors are you getting?

**Comment by AJPearson** [comment]
Thank you for letting me know regarding that! I wasn't aware it was referencing the page directly.
The errors were caused by me accidentally commenting out some of the code so no worries!
